apiVersion: v1
kind: List
metadata:
  name: Razee
  namespace: razee
  annotations:
    razee.io/git-repo: "{{{GIT_REMOTE}}}"
    razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
items:

# MongoDB Service resources
- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: mongo-pv-volume
    namespace: razee
    labels:
      type: local
  spec:
    storageClassName: manual
    capacity:
      storage: 10Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/mnt/data/mongo"
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: mongo-pv-claim
    namespace: razee
  spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: manual
    resources:
      requests:
        storage: 3Gi
- apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
  kind: Deployment
  metadata:
    name: mongo
    namespace: razee
  spec:
    selector:
      matchLabels:
        app: mongo
        role: master
        tier: backend
    replicas: 1
    template:
      metadata:
        labels:
          app: mongo
          role: master
          tier: backend
      spec:
        containers:
          - name: mongo
            image: mongo
            ports:
              - containerPort: 27017
            volumeMounts:
              - name: data
                mountPath: /data/db
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mongo-pv-claim
- apiVersion: v1
  kind: Service
  metadata:
    name: mongo
    namespace: razee
    labels:
      app: mongo
  spec:
    ports:
    - name: mongo
      port: 27017
      targetPort: 27017
    clusterIP: None
    selector:
      app: mongo
- apiVersion: v1
  kind: Secret
  metadata:
    name: razeedash-secret
    namespace: razee
  type: Opaque
  data:
    mongo_url: bW9uZ29kYjovL21vbmdvOjI3MDE3L3JhemVlZGFzaA==

# Razeedash resources
- apiVersion: "kapitan.razee.io/v1alpha1"
  kind: RemoteResource
  metadata:
    name: razeedash
    namespace: razee
    annotations:
      razee.io/git-repo: "{{{GIT_REMOTE}}}"
      razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
  spec:
    requests:
      - options:
          url: https://github.com/razee-io/Razeedash-api/releases/latest/download/resource.yaml
      - options:
          url: https://github.com/razee-io/Razeedash/releases/latest/download/resource.yaml
#ALB Resources
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: razeedash
    name: razeedash-lb
    namespace: razee
    annotations:
      razee.io/git-repo: "{{{GIT_REMOTE}}}"
      razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 3000
    selector:
      app: razeedash
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: razeedash-api
    name: razeedash-api-lb
    namespace: razee
    annotations:
      razee.io/git-repo: "{{{GIT_REMOTE}}}"
      razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 3333
    selector:
      app: razeedash-api
    type: LoadBalancer
